### ISSUE TITLE
Error in point sample

### ISSUE THREAD

**Issue by emannix** [ydhongHIT/PlainSeg#1]
Hi! I've just been trying to get this code to work, and I'm running into the following error

```python
2023-11-29 15:45:26,850 - mmseg - INFO - workflow: [('train', 1)], max: 80000 iters
2023-11-29 15:45:26,850 - mmseg - INFO - Checkpoints will be saved to /home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/work_dirs/mask2former_beit_base_parallel_separate_slim_640_80k_ade20k_ss by HardDiskBackend.
/home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg/lib/python3.8/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
Traceback (most recent call last):
  File "train.py", line 220, in <module>
    main()
  File "train.py", line 209, in main
    train_segmentor(
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/apis/train.py", line 169, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/models/segmentors/base.py", line 138, in train_step
    losses = self(**data_batch)
  File "/home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/models/segmentors/base.py", line 108, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/models/segmentors/encoder_decoder_mask2former.py", line 143, in forward_train
    loss_decode = self._decode_head_forward_train(x, img_metas,
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/models/segmentors/encoder_decoder_mask2former.py", line 87, in _decode_head_forward_train
    loss_decode = self.decode_head.forward_train(x, img_metas,
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/models/decode_heads/mask2former_lite_parallel_separate_slim_head.py", line 578, in forward_train
    losses = self.loss(all_cls_scores, all_mask_preds, gt_labels, gt_masks,
  File "/home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/models/decode_heads/mask2former_lite_parallel_separate_slim_head.py", line 404, in loss
    losses_cls, losses_mask, losses_dice = multi_apply(
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/core/utils/misc.py", line 21, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/models/decode_heads/mask2former_lite_parallel_separate_slim_head.py", line 314, in loss_single
    num_total_neg) = self.get_targets(cls_scores_list, mask_preds_list,
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/models/decode_heads/mask2former_lite_parallel_separate_slim_head.py", line 208, in get_targets
    neg_inds_list) = multi_apply(self._get_target_single, cls_scores_list,
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/core/utils/misc.py", line 21, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/unimelb.edu.au/nbloomfield/OneDrive/PhD/Repositories/aa_cloned-repositories/PlainSeg/mmseg/models/decode_heads/mask2former_lite_parallel_separate_slim_head.py", line 262, in _get_target_single
    gt_points_masks = point_sample(gt_masks.unsqueeze(1).float(), point_coords.repeat(num_gts, 1, 1)).squeeze(1)
  File "/home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg/lib/python3.8/site-packages/mmcv/ops/point_sample.py", line 279, in point_sample
    output = F.grid_sample(
  File "/home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg/lib/python3.8/site-packages/torch/nn/functional.py", line 3989, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: grid_sampler(): expected 4D or 5D input and grid with same number of dimensions, but got input with sizes [34, 1, 640, 640, 3] and grid with sizes [34, 12544, 1, 2]
```

I'm using a single GPU and the ADE20k dataset (config file is mask2former_beit_base_parallel_separate_slim_640_80k_ade20k_ss.py). For reference, this is my conda environment

```
name: plainseg
channels:
  - scikit-learn
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2023.11.17=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgomp=13.2.0=h807b86a_3
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.44.2=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=h59595ed_2
  - openssl=3.2.0=hd590300_1
  - pip=23.3.1=pyhd8ed1ab_0
  - python=3.8.18=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - mmcv-full==1.4.2
    - mmdet==2.22.0
    - mmsegmentation==0.20.2
    - prettytable==3.9.0
    - six==1.16.0
    - timm==0.4.12
    - torch==1.9.0+cu111
    - torchaudio==0.9.0
    - torchvision==0.10.0+cu111
prefix: /home/unimelb.edu.au/nbloomfield/anaconda3/envs/plainseg
```

Anyone else also run into this error?

**Comment by emannix** [comment]
Ooops, looks like I was using the wrong ADE20k dataset version. The right one can be found here!

https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/dataset_prepare.md#prepare-datasets
